### ISSUE TITLE
central cache freelist leak?

### ISSUE THREAD

**Issue by XinzeChi** [google/tcmalloc#118]
I’m running a process for a while, and I have a problem with the memory usage, which never decrease. 
The TCMalloc statistics says:

MALLOC:    10689905288 (10194.7 MiB) Bytes in use by application
MALLOC: +    284106752 (  270.9 MiB) Bytes in page heap freelist
MALLOC: +   2150254992 ( 2050.6 MiB) Bytes in central cache freelist
MALLOC: +      6489856 (    6.2 MiB) Bytes in transfer cache freelist
MALLOC: +     85912808 (   81.9 MiB) Bytes in thread cache freelists
MALLOC: +     56754176 (   54.1 MiB) Bytes in malloc metadata
MALLOC:   ------------
MALLOC: =  13273423872 (12658.5 MiB) Actual memory used (physical + swap)
MALLOC: +    621199360 (  592.4 MiB) Bytes released to OS (aka unmapped)
MALLOC:   ------------
MALLOC: =  13894623232 (13250.9 MiB) Virtual address space used
MALLOC:
MALLOC:         846714              Spans in use
MALLOC:            110              Thread heaps in use
MALLOC:           8192              Tcmalloc page size

Why there are so many bytes which is not release in central cache freelist ?
Any kind of help will be appreciated. Thanks in advance

**Comment by ckennelly** [comment]
(This might be a profile from https://github.com/gperftools/gperftools, since there's no mention of the per-CPU cache.)

The central freelist holds spans of multiple objects that have not been fully reassembled.  So if there's a span of memory with 8 objects, all 8 of those objects must be returned to the central freelist before the span can be deallocated to the page heap.
