### ISSUE TITLE
Aggregate duplicate stacks in allocation sample

### ISSUE THREAD

**Issue by SrivastavaAnubhav** [google/tcmalloc#161]
I used `StartAllocationProfiling` to get a list of samples and some of the sample stacks were duplicates of each other. Is this expected? Does it make sense to sum the `sum` and `count` fields of each sample with the same stack if I'm trying to get the total number of allocated bytes / allocations?

Also, is there a way to achieve the functionality of the old gperftools growth endpoint? I.e. to only report allocations that **do not** have a corresponding deallocation in the sampling period? This seems like the opposite of the lifetime profiler, but I'm not sure how I would achieve this.

**Comment by SrivastavaAnubhav** [comment]
Makes sense, thank you @ckennelly!

**Comment by SrivastavaAnubhav** [comment]
Actually one more follow-up @ckennelly: Is the allocation profiler strictly less powerful than the lifetime profiler? Why would I use the allocation profiler over the lifetime profiler?

**Comment by SrivastavaAnubhav** [comment]
@ckennelly I noticed that for censored samples, the count is set to negative and the stack is replaced with the deallocation stack. Do you know the reasoning behind this? The former isn't too big a deal (though I don't understand the benefit), but the latter makes it impossible to associate with allocations that had a deallocation and allocations (from the same place) that did not.

**Comment by snehasish** [comment]
> censored samples, the count is set to negative and the stack is replaced with the deallocation stack

I think you are looking at a [deallocation](https://github.com/google/tcmalloc/blob/19b094a9afaf9f37caac06003ba980bcc3b8b276/tcmalloc/deallocation_profiler.cc#L553-L557) record, not a censored allocation record.

The allocation sample accessed via the DeallocationStackTraceTable::Iterate interface [has positive count](https://github.com/google/tcmalloc/blob/19b094a9afaf9f37caac06003ba980bcc3b8b276/tcmalloc/deallocation_profiler.cc#L538-L547) (note that we do not emit a deallocation pair). When emitting the [censored allocation in the profile proto](https://github.com/google/tcmalloc/blob/19b094a9afaf9f37caac06003ba980bcc3b8b276/tcmalloc/internal/profile_builder.cc#L553-L564) the count is positive and the values are stored in the index identified by sample types, `censored_allocated_objects` and `censored_allocated_bytes` (i.e. index 4 and 5).

Please share a pointer to the code/example if you still see this behaviour because that is unintended.

**Comment by SrivastavaAnubhav** [comment]
Ah ok I might have been looking at a deallocation record, I'll double check that. I'm using Profile::Iterate on the output of `StartLifetimeProfiling`, so I'm not using the profile proto. 

Let me take a step back: I want to be able to output the following two things (not necessarily for the same profile):
1. The stack traces of all allocated objects.
2. The stack traces of all objects that were allocated but not deallocated.
My approach for (1) is to combine all `Sample`s that have count > 0, and for (2) to combine all `Sample`s that have count > 0 and `is_censored = true`. Does that seem correct?

**Comment by snehasish** [comment]
Yes, that looks correct.
