### ISSUE TITLE
BUILD fail

### ISSUE THREAD

**Issue by tz301** [google/tcmalloc#46]
I just git clone this project and using `bazel test //tcmalloc:cpu_cache_test`，I meet following errors.

![image](https://user-images.githubusercontent.com/35760938/91425612-f49a3100-e88d-11ea-969b-6093ff860cbd.png)

BTW, I'm using Ubuntu 18.04, gcc 5.5.0 and 0.24.1.

**Comment by ckennelly** [comment]
This doesn't seem to reproduce for me.  I'm not sure if that's due to using an older version of Bazel.

On an unrelated note, GCC 5.5.0 is fairly old and only implements C++11 ([at least according to its manual](https://gcc.gnu.org/onlinedocs/gcc-5.5.0/gcc/Standards.html#C_002b_002b-Language)).  At present, this project requires C++17 to build.
