### ISSUE TITLE
Intercepting file I/O can cause deadlock in TCMalloc

### ISSUE THREAD

**Issue by vlovich** [google/tcmalloc#78]
TCMalloc attempts to read files in `/sys/` (via Abseil to get CPU frequency & whatnot) while holding a spinlock in `Static::SlowInitIfNecessary`. If run with a preloaded library that intercepts glibc I/O calls & then does a `dlsym`, this can cause a deadlock because the `dlsym` will cause TCMalloc to try to reenter it's initialization routine while holding the spinlock.

Admittedly this is grotty behavior on the part of the intercepting library (used to implement the [Ekam](https://github.com/capnproto/ekam) build system). I'm going to push a PR there too to work around this. However, a simple fix here on the part of TCMalloc would be to call the Abseil functions that can read from `/sys/` before entering the critical section. Since Abseil caches the values from `/sys/`, this would remove the need for the workaround. Avoiding doing I/O while holding critical sections is probably a good idea anyway.

**Comment by vlovich** [comment]
Never mind. There's not really anything that TCMalloc can apparently do to fix this since there's a `call_once` protecting reading these files so the potential for reentrancy here is a problem that must be resolved by the intercepting library.

**Comment by kentonv** [comment]
This still feels like a bug to me.

It sounds like tcmalloc performs complex operations like opening and reading files which must complete before the first malloc() can succeed. It seems really precarious for tcmalloc to assume that such functions won't themselves try to allocate memory.

In the particular case we ran into, memory allocation was performed by `libdl.so`, the dynamic linker. Admittedly, the use of `LD_PRELOAD` to intercept `open()` was making things more complicated then normal, but in the end it was still the dynamic linker itself that decided it needed to malloc().

If the dynamic linker can do memory allocation, then it seems like tcmalloc really should not be making any library calls at all during its initialization.

**Comment by ckennelly** [comment]
`man 7 signal-safety` lists `open`, `read`, and `close` as async signal safe, so these are generally not going to allocate, since `malloc` itself is not async signal safe.  Putting aside whether `malloc` should call these, I think an intercepting library needs to preserve these signal safety guarantees.

Separately, looking at TCMalloc:
* Prior to ce8bea383357e6baa07ae171f7af4f4b5594fbb3, we had fairly elaborate interception defenses for `clock_gettime`, directly looking up the VDSO.  That came at a performance cost, since we don't actually need human-interpretable time units here.
* While we could defer initializing some of these data structures, it'd come with some complexity cost.  Additionally, we'd probably still end up holding an important lock when we do so, since they're normally accessed under locks.  The allocator might be in a state where it can handle many small allocations from `libdl.so` by hitting a cache *but* occasionally it'll fail.
* That leaves making `malloc` reentrant.  While this could be validated via a carefully structured test, it wouldn't get substantial exposure to production usage that could otherwise find subtle bugs/test gaps.

**Comment by ahh** [comment]
I think it's pretty crucial to make async-signal-safe syscalls...async-signal-safe.  I do know from experience that's rough on interruptors, but not having that really puts malloc implementors in a hard place.

**Comment by kentonv** [comment]
Yeah, I'd argue the real fault lies with `dlsym()` deciding it needs to malloc just to look up a symbol name in an already-loaded library. AFAICT that means it's pretty much impossible to do LD_PRELOAD-based interception of `open()` in an async-signal-safe way. Our interception code was otherwise signal-safe...

tcmalloc could try to be helpful by, maybe, having some mechanism to satisfy mallocs that happen during initialization without deadlocking. But you're right that it has no obligation to do so.

Everybody is "technically correct" here but the result is that certain things that would be useful are not possible.
