### ISSUE TITLE
Is kPeakHeap profile type equivalent to GetHeapGrowthStack?

### ISSUE THREAD

**Issue by vlovich** [google/tcmalloc#91]
The old gperftools had a `MallocExtension::instance()->GetHeapGrowthStacks` function that returns the stacks causing growth in the address space size. A coworker suggested similar data might be obtained by doing `MallocExtension::SnapshotCurrent(ProfileType::kPeakHeap)` in this updated implementation. I'm wondering if that is indeed similar use or if there's just no mapping for that old function yet.

Apologies if this is not a great support channel. I don't see a mailing list/google group recommended for questions.

**Comment by ckennelly** [comment]
Peak heap profiles are generally recommended for debugging memory usage.

Growth tracking only captured when the virtual address space size increased, but since memory can be returned to the operating system (either on demand, from calls to `MallocExtension::ReleaseMemoryToSystem`, or automatically as part of [Temeraire's HugeCache](https://google.github.io/tcmalloc/temeraire.html)), the callstacks don't necessarily correspond to increases in actual physical memory usage.

**Comment by vlovich** [comment]
Thanks!
