### ISSUE TITLE
Malloc extension to support process forking

### ISSUE THREAD

**Issue by slon** [google/tcmalloc#95]
Hello,

I would like to discuss malloc extension that would allow safely using malloc in the child process after using fork.

My use case for such extension is process snapshotting "à la redis". We got a usual multi-threaded server. Once in 15 minutes 
we need to make process state snapshot and upload it to the distributed file system. In case of a crash or process restart, we load that snapshot and recover current state.

We rely heavily on operating system Copy-on-Write. Server make fork() system call and continues serving user requests after that. Child process walks snapshot of the process memory and streams serialized snapshot back to the parent through a pipe. Code for building the snapshot performs allocations, so allocator should continue working in the child.

From the point of view of the child process, fork() freezes all other threads. As long as freezed threads don't hold any locks, everything should continue working as normal. Code thread safety guarantees that. Some memory may leak, but we don't care about that.

Currently, tcmalloc does not support that use case. For example, if other thread holds page_lock during fork, page_lock will remain locked forever in the child.

The fix is simple: Acquire all internal tcmalloc locks before fork() and release them after fork() returns.
You can see my implementation here: https://github.com/slon/tcmalloc/commit/bf24b32085a496556829e290601cec6e61e1fc92
It is based on the old tcmalloc version that we use internally.

What do you think about such extension?

**Comment by ckennelly** [comment]
It's difficult to make things work safely after `fork` in a multi-threaded environment, absent immediately `exec`'ing (but that defeats the snapshotting goal you mentioned).  Our production environment exclusively immediately `exec`'s after `fork`, so this is an untested configuration.

I think the consequence of this is that we cannot take this extension.

* Because this isn't a routinely used configuration, it's possible for subtle bugs to be introduced and not noticed for some time until they materialize as deadlocks.
* There are a number of lock-like structures in TCMalloc which can potentially block.  For example, several `absl::call_once` instances trigger initialization on first use, but populating these eagerly would use more resources than necessary.  Triggering initialization of the `once_flag` state with a no-op initializer could avoid that, but come at the consequence of correctness bugs for still-inflight threads that assume that initialization has actually completed.
* TCMalloc depends on Abseil, which could also have its own internal locks/initialization as well.
